name: Java CI/CD with ArgoCD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Deploy to ArgoCD
      uses: argoproj-labs/argocd-action@v2
      with:
        server: ${{ secrets.ARGOCD_SERVER }}
        token: ${{ secrets.ARGOCD_TOKEN }}
        namespace: 'your-argo-namespace'
        application: 'your-application-name'
        source: 'git::https://github.com/yourusername/your-repo.git'
        sync-options: '--sync-policy=auto'