name: Java Maven Build and Docker Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Use the docker key
      run: echo ${{ secrets.DOCKER_REPO }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_REPO }}/${{ github.repository }}:latest .

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_REPO }}/${{ github.repository }}:latest