name: Revert Previous Commit

on:
  workflow_dispatch:  # O rollback é acionado manualmente

jobs:
  revert_commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Clona todo o histórico do repositório

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Get previous commit ID
      id: prev-commit
      run: echo "commit_id=$(git rev-parse HEAD~1)" >> $GITHUB_ENV

    - name: Revert previous commit
      run: |
        git revert --no-commit ${{ env.commit_id }}
        git commit -m "Reverting commit ${{ env.commit_id }}"
        git push origin HEAD